[versions]

jdkVersion = "17"
koog = "0.6.1"
kotlin = "2.3.10"
ktlint = "1.8.0"

[libraries]

koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
