[versions]

jdkVersion = "17"
koog = "0.5.4"
kotlin = "2.2.21"
ktlint = "1.8.0"

[libraries]

koog-prompt-llm = { module = "ai.koog:prompt-llm", version.ref = "koog" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
